/**
 * Generates a Product Requirements Document (PRD) in Markdown format.
 */
import type { TaskPlan } from './types.js';

/**
 * Render a TaskPlan as a Markdown PRD string.
 */
export function generatePRD(plan: TaskPlan): string {
  const lines: string[] = [];

  lines.push(`# PRD: ${plan.title}`);
  lines.push('');
  lines.push(`> Generated by agent-task-loop on ${plan.createdAt}`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(plan.description);
  lines.push('');

  // Design decisions
  if (plan.designDecisions.length > 0) {
    lines.push('## Design Decisions');
    lines.push('');
    for (const dd of plan.designDecisions) {
      lines.push(`**Q: ${dd.question}**`);
      lines.push('');
      lines.push(`> ${dd.answer}`);
      lines.push('');
    }
  }

  // Sub-tasks / todo list
  lines.push('## Task Breakdown');
  lines.push('');
  lines.push(
    '| ID | Title | Agent | Dependencies | Status |',
  );
  lines.push('|---|---|---|---|---|');
  for (const task of plan.subTasks) {
    const deps = task.dependencies.length
      ? task.dependencies.join(', ')
      : '—';
    lines.push(
      `| ${task.id} | ${task.title} | \`${task.agent}\` | ${deps} | ${task.status} |`,
    );
  }
  lines.push('');

  // Todo checklist
  lines.push('## Todo Checklist');
  lines.push('');
  for (const task of plan.subTasks) {
    lines.push(`- [ ] **[${task.id}]** ${task.title} — *assigned to \`${task.agent}\`*`);
    lines.push(`  ${task.description}`);
  }
  lines.push('');

  // Completion criteria
  lines.push('## Completion Criteria (Definition of Done)');
  lines.push('');
  for (const criterion of plan.completionCriteria) {
    lines.push(`- [ ] ${criterion}`);
  }
  lines.push('');

  return lines.join('\n');
}
